name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:


jobs:
  build:

    env:
      platform: linux

    runs-on: ubuntu-latest

    steps:
      - name: "Show message"
        run: echo "Hello World!"

      - name: "Show varibles"
        if: ${{ env.platform == 'linux' }}
        run: |
         echo "Varible is $(env.platform)"
        
        

